language: ruby
os: osx
cache: bundler
# We try to support the following system Ruby versions and test a similar version here.
#   macOS 10.15: Catalina (2019) - Ruby 2.6.3
#   macOS 10.14: Mojave (2018) - Ruby 2.3.7
#   macOS 10.13: High Sierra (2017) - Ruby 2.3.3
rvm: 2.4.10 # 2.3.x doesn't work well on Travis osx
branches:
  only:
    - master
script:
  - "bundle exec exe/md2key" # Test only syntax and basic functionality
